#!/bin/bash

rm log/test.log
if (echo $1 | grep ^feature)
then
	env RAILS_ENV=test cucumber $* 2>&1 | tee 1test.out
else
  if (echo $1 | grep ^spec)
  then
	env RAILS_ENV=test spec $* 2>&1 | tee 1test.out
  else
    echo > 1test.out
    for x in $*
    do
      ruby $x 2>&1 | tee -a 1test.out
    done
  fi
fi
vi 1test.out log/test.log
