#!/bin/bash

if [ "$1" == 'cuc' ] ; then
  env RAILS_ENV=test rake cucumber --trace 2>&1 | tee cuc.out
elif [ "$1" == 'spc' ] ; then
  env RAILS_ENV=test rake spec --trace 2>&1 | tee spc.out
else 
  env RAILS_ENV=test rake test --trace 2>&1 | tee tst.out
fi

