languages:
  Ruby: true
  JavaScript: true
  PHP: false
  Python: false
engines:
  rubocop:
    enabled: true
    config: .codeclimate-rubocop.yml
    checks:
      Rubocop/Style/SpaceInsideStringInterpolation:
        enabled: false
  golint:
    enabled: false
  gofmt:
    enabled: false
  eslint:
    enabled: true
  csslint:
    enabled: true
ratings:
   paths:
   - card/lib/**
   - card/mod/**
   - wagn/lib/**
   - wagn/rails/**
   - "**.rb"
exclude_paths:
- wagn/rails/assets/**/*
- card/mod/**/lib/javascript/*.js
- card/mod/03_machines/lib/javascript/**/*
- card/mod/03_machines/lib/javascript/**/*
- card/mod/06_bootstrap/lib/javascript/**/*
- card/db/**/*
- card/spec/**/*
- wagn/spec/**/*
