AllCops:
  Exclude:
    - "vendor/**/*"
    - "card/db/schema.rb"
    - "card/tmpsets/**/*"
    - "card/mod/06_bootstrap/lib/**/*"
    - "card/mod/03_machines/lib/javascript/**/*"
    - "card/mod/03_machines/lib/stylesheets/**/*"
    - "wagn/lib/wagn/generators/wagn/templates/Gemfile"

Style/CommentAnnotation:
  Enabled: true
Style/CollectionMethods:
  # Mapping from undesired method to desired_method
  # e.g. to use `detect` over `find`:
  #
  # CollectionMethods:
  #   PreferredMethods:
  #     find: detect
  Description: Preferred collection methods.
  Enabled: true
  PreferredMethods:
    collect: map
    collect!: map!
    detect: find
    find_all: select
    reduce: inject
Style/DotPosition:
  EnforcedStyle: leading
Style/Encoding:
  Description: Use UTF-8 as the source file encoding.
  Enabled: false
  EnforcedStyle: when_needed
Style/GuardClause:
  Description: Check for conditionals that can be replaced with guard clauses
  Enabled: true
Style/MethodDefParentheses:
  Description: Checks if the method definitions have or don't have 252
  Enabled: true
  EnforcedStyle: require_no_parentheses
Style/RegexpLiteral:
  Description: Use %r for regular expressions matching more than
               `MaxSlashes` '/' characters. Use %r only for regular expressions
               matching more than `MaxSlashes` '/' character.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#percent-r
  Enabled: true
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space
Metrics/MethodLength:
  Enabled: true
  CountComments: false
  Max: 15
Style/ExtraSpacing:
  Description: Do not use unnecessary spacing.
  Enabled: false
Lint/AssignmentInCondition:
  Enabled: true
  AllowSafeAssignment: true
Style/Alias:
  EnforcedStyle: prefer_alias_method
Style/EmptyCaseCondition:
  Enabled: false
Style/FormatString:
  EnforcedStyle: percent
  SupportedStyles:
    - format
    - sprintf
    - percent