source 'http://rubygems.org'

gem 'wagn'<%= ", :path=>'#{@wagn_path}'"  if @wagn_path.present? %>

<%= database_gemfile_entry -%>

# A javascript runtime is required for JavaScript cards.
<% if RUBY_PLATFORM =~ /darwin/ -%>
# Macs have one included, but on other platforms you'll need this or another runtime
# gem 'therubyracer'
<% else -%>
gem 'therubyracer'
<% end -%>

<% if options['mod-dev'] -%>
group :test do
  gem 'rspec-rails', "~> 2.6"   # behavior-driven-development suite
  gem 'spork', '>=0.9'
  # gem 'simplecov' # code coverage analysis tool
end

group :test, :development do
  gem 'rails-dev-tweaks'
  gem 'sprockets' # just so above works
  if RUBY_VERSION =~ /^2/
		gem 'byebug' 
	else
		gem 'debugger'
	end
end

<% end -%>

<% if options['core-dev'] -%>  
group :assets do
  gem 'jquery-rails',  '~> 3.1'                # main js framework, along with rails-specific unobtrusive lib
  gem 'jquery-ui-rails',  '~> 4.2'             # main js framework, along with rails-specific unobtrusive lib
  gem "jquery_mobile_rails", "~> 1.4.1"

  gem 'tinymce-rails', '~> 3.4'                # wysiwyg editor
end

group :development do
  gem 'rails-dev-tweaks'
  gem 'sprockets' # just so above works
end

group :test do
  gem 'rspec-rails', "~> 2.6"                  # behavior-driven-development suite
  gem 'spork', '>=0.9'                                           
  gem 'rr'#, '=1.0.0'
  
	gem 'simplecov', '~> 0.7.1', :require => false  #test coverage
    
  gem 'guard-rspec', '~> 4.2'                  # trigger test runs based on file edits
  if RUBY_PLATFORM =~ /darwin/
    gem 'terminal-notifier-guard', '~> 1.5'    # use growler notifications on macs
  end

  # CUKES see features dir
  gem 'cucumber-rails', '~> 1.3', :require=>false # feature-driven-development suite
  gem 'capybara', '~> 2.2.1'                     # note, selectors were breaking when we used 2.0.1
  gem 'selenium-webdriver', '~> 2.39'
#  gem 'capybara-webkit'
  gem 'launchy'                                # lets cucumber launch browser windows

  gem 'timecop', '=0.3.5'                      # not clear on use/need.  referred to in shared_data.rb 
  # NOTE: had weird errors with timecop 0.4.4.  would like to update when possible


  gem 'email_spec'                             # 
  gem 'database_cleaner', '~> 0.7'             # used by cucumber for db transactions

  gem 'turn', "~>0.8.3", :require => false      # Pretty printed test output.  (version constraint is to avoid minitest requirement)
  gem 'minitest', "~>4.0"
end

gem 'ruby-prof', '~>0.12.1', :group=>:profile  # profiling

group :debug do
  if RUBY_VERSION =~ /^2/
		gem 'byebug' 
	else
		gem 'debugger'
	end
end
<% end %>
