module AllSets
  Wagn::Set::Right::Xaccount
  Wagn::Set::Right::Xsol
  #Wagn::Set::Type::Image
  Wagn::Set::Type::Etherpad
  Wagn::Set::Type::Layout
  Wagn::Set::Type::Role
  Wagn::Set::Type::File
  Wagn::Set::Type::User
  Wagn::Set::Type::InvitationRequest
  Wagn::Set::Type::Search
  Wagn::Set::Type::Number
  Wagn::Set::Type::Basic
  #Wagn::Set::Type::Phrase
  Wagn::Set::Type::HTML
  Wagn::Set::Type::Pointer
  Wagn::Set::Type::Cardtype
  Wagn::Set::Type::Set
  Wagn::Set::Self::Settings
end
