#!/usr/bin/env ruby
require File.dirname(__FILE__) + '/../config/boot'
require File.dirname(__FILE__) + '/../config/environment'
require 'lib/util/dumper'    
usage = "Usage: export <format>  > outfile"
format = ARGV[0] || 'xml'
Wagn::Dumper.new.send( "dump_#{format}" )