#!/bin/sh                 

# 1. TURN FULLTEXT OFF in wagn.rb

dropdb wagn_test_template
createdb wagn_test_template
set_database wagn_test_template 
rake db:migrate
rake populate_template_database --trace
#rake extract_fixtures



