#!/bin/sh

if [ "$1" = "" ]; then   
  echo "Usage: pg_dump_data <pg_dump args,ie:database> > outputfile"
  exit 0
fi                     
               
PG_DUMP=`which pg_dump`
PG_ARGS="$1 $2 $3 $4 $5"

TABLES="cards cardtypes permissions revisions roles roles_users"
TABLES="$TABLES schema_migrations settings system users wiki_references"

for T in $TABLES; do
  $PG_DUMP --data-only --table $T $PG_ARGS
done
