#!/usr/bin/env ruby
# This command will automatically be run when you run "rails" with Rails 3 gems installed from the root of your application.

APP_PATH = File.expand_path('../../lib/wagn/application',  __FILE__)
require File.expand_path('../../lib/wagn/boot',  __FILE__)
require 'rails/commands'
