#!/bin/sh
if [ "$1" = "" ]; then
   echo "Usage: select_for_request <request_path>";
   echo "Note: assumes mongrel running in dev mode on port 3000";
   echo "will erase your development log";
else 
    echo "" | cat > log/development.log ; 
   	echo ""
   	curl http://localhost:3000/$1 > /dev/null 2>&1   
 	cat log/development.log | egrep -i '(select|SQL)' | grep -v 'a.attname' | grep -v 'tablename' | grep -v 'CACHE' > tmp/queries
    cat tmp/queries        
   
	 echo -n "Total Time: " 
    cat tmp/queries  | awk '{print $3}' | grep '(' | ruby -ne 'BEGIN{$n=0}; $n+=$_.gsub(/\((.*)\)/,%q{\1}).to_f; END{ print $n}'
    echo -n "   Queries:"
    cat tmp/queries  | wc -l  
	 echo ""
fi   
             
